name: Generic CI
on: [push]

jobs:
  check-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -R

{{TEST_STEPS}}