name: Python CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: {{WORKING_DIRECTORY}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
{{LINT_STEPS}}
{{TEST_STEPS}}
      - name: Prepare artifact
        run: |
          TEMP_DEST="${{ runner.temp }}/staging_area"
          rm -rf "$TEMP_DEST" # Nettoyage si un job précédent a échoué
          mkdir -p "$TEMP_DEST"

          cp -rp . "$TEMP_DEST/"
 
          cd "$TEMP_DEST"
          rm -rf .git .github venv .venv __pycache__ .pytest_cache .cache

          mkdir -p "$GITHUB_WORKSPACE/artifact_final"
          cp -rp . "$GITHUB_WORKSPACE/artifact_final/"
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }} 
          path: artifact_final/
          retention-days: 7